site_name: Bali
site_description: Simplify Cloud Native Microservices development base on FastAPI and gRPC.
site_url: https://bali-framework.github.io/bali/

theme:
  name: material
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: "Switch to dark mode"
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      primary: 'blue'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'

repo_name: bali-framework/bali
repo_url: https://github.com/bali-framework/bali
edit_uri: ""

nav:
- 简介: index.md
- App: application.md
- 数据库: database.md
- 缓存: cache.md
- 资源: resource.md
- 事件: event.md
- Schema: schema.md
- Utility: utility.md
- 测试: testing.md
- 版本记录: release-notes.md

markdown_extensions:
  - mkautodoc
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  alternate:
    - name: English
      link: /bali/
      lang: en
    - name: 简体中文
      link: /bali/zh/
      lang: zh
